version: '3.9'

services:
  local-dynamodb:
    image: amazon/dynamodb-local
    container_name: tgstore-mvp-dynamodb
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    user: root
    ports:
      - "9009:8000"
    environment:
      - TZ=Europe/Kaliningrad
    volumes:
      - "./dynamodb:/home/dynamodblocal/data"
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
    working_dir: /home/dynamodblocal
