version: '3.9'

services:
  local-dynamodb:
    image: amazon/dynamodb-local
    container_name: local-bot-dynamodb
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    user: root
    ports:
      - "9010:8000"
    volumes:
      - "./dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal
